{% set name = "CellProfiler" %}
{% set version = "3.1.9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/CellProfiler/{{ name  }}/archive/v{{ version }}.tar.gz
  sha256: "44e10c57980b4fd20f530dd5dc8c8bea9c870000601e12d500c27d145ca2ee9f"
build:
  number: 3
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv"
  skip: True  # [win or osx or py3k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - backports.functools_lru_cache
    - cython
    - openjdk 8.*
    - pytest
    
  run:
    - python
    - appdirs
    - boto3
    - centrosome 
    - docutils
    - h5py
    - ipywidgets
    - inflect =2.1.0
    - joblib
    - jupyter
    - libtiff
    - libxml2
    - libxslt
    - lxml
    - packaging
    - pip
    - mahotas
    - matplotlib-base  >=2.0.0,!=2.1.0,<3
    - mysqlclient
    - numpy
    - javabridge
    - prokaryote
    - python-bioformats =1.5.2
    - pyzmq =15.3.0
    - raven
    - requests
    - scikit-image =0.14.*
    - scikit-learn >=0.20
    - scipy >=1.2
    - pillow
    - sphinx
    - tifffile
    - networkx ==2.2.*
    - vigra
    - future
    
test:
  imports:
    - cellprofiler

about:
  home: https://github.com/CellProfiler/CellProfiler
  license: 3-clause BSD
  license_family: BSD
  license_file: LICENSE
  summary: "CellProfiler is free, open-source software for quantitative analysis of biological images"
  description: |
     CellProfiler is free, open-source software for quantitative analysis of biological images.
extra:
  identifiers:
    - biotools:CellProfiler
  recipe-maintainers:
    - sunyi000
